import { getLocale } from '../i18n.js'
import { LANGUAGES } from '../components/LanguagePicker.js'
import { loadCatalog } from '../data/catalog.js'
import { Header } from '../components/Header.js'

const LEVELS = ['intro', 'core', 'college', 'research']

const MODELS = [
  { value: '', label: '— default —' },
  { value: 'gemma3', label: 'gemma3 (Ollama)' },
  { value: 'gemma4', label: 'gemma4 (Ollama)' },
  { value: 'sonnet', label: 'sonnet (Claude)' },
  { value: 'haiku', label: 'haiku (Claude)' },
  { value: 'opus', label: 'opus (Claude)' },
]

function parseLevelLang(file) {
  const m = file.match(/output\/([^.]+)\.([^/]+)\//)
  return m ? { level: m[1], lang: m[2] } : { level: 'college', lang: 'en' }
}

function parseModel(file) {
  // Matches output/{level}.{lang}/{model}/html/ — returns model name or ''
  const m = file.match(/output\/[^/]+\/([^/]+)\/html\//)
  return m ? m[1] : ''
}

function conceptFilename(file) {
  return file.replace(/^.*\//, '')
}

function buildUrl(domain, file, level, lang, model) {
  const fname = conceptFilename(file)
  const modelPart = model ? `${model}/` : ''
  return `${import.meta.env.BASE_URL}domains/${domain}/output/${level}.${lang}/${modelPart}html/${fname}`
}

// Cache existence checks — pre-populated from catalog data so known files
// never incur an extra HTTP round-trip
const _existsCache = new Map()

function _markKnownUrls(domain, files) {
  files.forEach(f => {
    const url = `${import.meta.env.BASE_URL}domains/${encodeURIComponent(domain)}/${f.file}`
    _existsCache.set(url, true)
  })
}

async function _checkExists(url) {
  if (_existsCache.has(url)) return _existsCache.get(url)
  try {
    const res = await fetch(url)
    if (!res.ok) { _existsCache.set(url, false); return false }
    const text = await res.text()
    const exists = text.includes('spl-credit') || text.includes('Generated by')
    _existsCache.set(url, exists)
    return exists
  } catch (_) { _existsCache.set(url, false); return false }
}

function _clearExistsCache() {
  _existsCache.clear()
}

function _notFoundHtml(fname, model, lang, level) {
  const conceptName = decodeURIComponent(fname).replace(/^(?:concept|book)_/, '').replace(/_/g, ' ').replace(/\.html$/, '')
  const modelLabel = model || 'default'
  return `<!DOCTYPE html><html><body style="font-family:system-ui,sans-serif;padding:48px 40px;color:#374151;background:#fafafa;min-height:100vh">
    <h2 style="color:#1e3a5f;margin:0 0 16px;font-size:1.3rem">Content Not Available</h2>
    <p style="margin:0 0 12px;font-size:0.9rem;color:#6b7280">No page exists for this combination:</p>
    <div style="background:#fff;border:1px solid #e0e3e8;border-radius:8px;padding:16px 20px;margin-bottom:24px;display:inline-block">
      <div style="margin-bottom:6px"><span style="font-weight:600;color:#374151;min-width:80px;display:inline-block">Model:</span><span style="color:#2563eb">${modelLabel}</span></div>
      <div style="margin-bottom:6px"><span style="font-weight:600;color:#374151;min-width:80px;display:inline-block">Level:</span><span style="color:#2563eb">${level}</span></div>
      <div><span style="font-weight:600;color:#374151;min-width:80px;display:inline-block">Language:</span><span style="color:#2563eb">${lang}</span></div>
    </div>
    <p style="color:#6b7280;font-size:0.88rem;line-height:1.6">Please generate the concept book for <strong style="color:#1e3a5f">${conceptName}</strong> first via the Concept-Graph page.</p>
  </body></html>`
}

// ── DOM helpers ───────────────────────────────────────────────────────────────

function makeSelect(options, current, cls) {
  const sel = document.createElement('select')
  if (cls) sel.className = cls
  options.forEach(({ value, label }) => {
    const opt = document.createElement('option')
    opt.value = value
    opt.textContent = label
    if (value === current) opt.selected = true
    sel.appendChild(opt)
  })
  return sel
}

function makeControlRow(label, state, onChange, onRefresh) {
  const row = document.createElement('div')
  row.className = 'cb-book-pane__controls'
  if (label) {
    const lbl = document.createElement('span')
    lbl.className = 'cb-book-pane__label'
    lbl.textContent = label
    row.appendChild(lbl)
  }
  const modelSel = makeSelect(MODELS, state.model, 'cb-book-pane__select')
  modelSel.title = 'Model'
  modelSel.addEventListener('change', () => onChange('model', modelSel.value))
  row.appendChild(modelSel)

  const levelSel = makeSelect(
    LEVELS.map(v => ({ value: v, label: v.charAt(0).toUpperCase() + v.slice(1) })),
    state.level, 'cb-book-pane__select'
  )
  levelSel.title = 'Level'
  levelSel.addEventListener('change', () => onChange('level', levelSel.value))
  row.appendChild(levelSel)

  const langSel = makeSelect(
    LANGUAGES.map(l => ({ value: l.code, label: l.label })),
    state.lang, 'cb-book-pane__select'
  )
  langSel.title = 'Language'
  langSel.addEventListener('change', () => onChange('lang', langSel.value))
  row.appendChild(langSel)

  if (onRefresh) {
    const refreshBtn = document.createElement('button')
    refreshBtn.type = 'button'
    refreshBtn.className = 'cb-book-pane__refresh'
    refreshBtn.title = 'Refresh — re-check for content that just finished generating'
    refreshBtn.textContent = '🔄'
    refreshBtn.addEventListener('click', onRefresh)
    row.appendChild(refreshBtn)
  }

  return row
}

// ── TOC sidebar ────────────────────────────────────────────────────────────────

function _fillTocSection(tocSection, leftFrame, { onConceptClick }) {
  tocSection.innerHTML = ''

  try {
    const doc = leftFrame.contentDocument
    const nav = doc?.querySelector('nav.toc')
    if (!nav) {
      tocSection.innerHTML = '<div style="color:#90b4e8;font-size:11px;padding:4px 0">No table of contents for this page.</div>'
      return
    }

    const heading = document.createElement('div')
    heading.style.cssText = 'font-size:.75rem;letter-spacing:.1em;text-transform:uppercase;color:#90b4e8;margin-bottom:14px;font-family:system-ui,sans-serif;font-weight:700'
    heading.textContent = 'Contents'
    tocSection.appendChild(heading)

    const navOl = nav.querySelector('ol')
    if (navOl) {
      const ol = document.createElement('ol')
      ol.style.cssText = 'list-style:decimal inside;padding:0;margin:0;flex:1'
      navOl.querySelectorAll('li').forEach(li => {
        const a = li.querySelector('a')
        if (!a) return
        const isTarget = li.classList.contains('toc-target')
        const newLi = document.createElement('li')
        newLi.style.cssText = `margin-bottom:7px;font-size:.85rem;line-height:1.4;font-family:system-ui,sans-serif${isTarget ? ';font-weight:700' : ''}`
        const newA = document.createElement('a')
        newA.textContent = a.textContent
        newA.href = '#'
        newA.style.cssText = `text-decoration:none;color:${isTarget ? '#fff' : '#a8c8f0'}`
        newA.addEventListener('mouseover', () => { newA.style.color = '#fff' })
        newA.addEventListener('mouseout', () => { newA.style.color = isTarget ? '#fff' : '#a8c8f0' })
        newA.addEventListener('click', e => { e.preventDefault(); onConceptClick(a.getAttribute('href')) })
        newLi.appendChild(newA)
        ol.appendChild(newLi)
      })
      tocSection.appendChild(ol)
    }

    const credit = nav.querySelector('.spl-credit')
    if (credit) {
      const div = document.createElement('div')
      div.style.cssText = 'margin-top:auto;padding-top:14px;border-top:1px solid rgba(255,255,255,0.15);font-size:11px;color:#90b4e8;font-family:system-ui,sans-serif'
      div.textContent = 'Generated by SPL'
      tocSection.appendChild(div)
    }
  } catch (_) {}
}

function hideTocInFrame(frame) {
  try {
    const doc = frame.contentDocument
    if (!doc) return
    const style = doc.createElement('style')
    style.textContent = 'nav.toc { display: none !important; } .page { grid-template-columns: 1fr !important; } h1.book-title + section > h2:first-child { display: none !important; }'
    doc.head.appendChild(style)
  } catch (_) {}
}

// ── Nav sidebar data loaders ──────────────────────────────────────────────────

async function _loadDomains() {
  try {
    const catalog = await loadCatalog()
    return catalog.map(d => d.id)
  } catch (_) { return [] }
}

async function _loadDomainBooks(domainId) {
  try {
    const catalog = await loadCatalog()
    const raw = catalog.find(e => e.id === domainId) ?? {}
    const books = (raw.books || []).map(b => ({ file: b.file, label: b.target.replace(/_/g, ' ').trim() || b.target, model: b.model || parseModel(b.file) }))
    const concepts = (raw.generated_concepts || []).map(c => ({ file: c.file, label: c.label, model: c.model || parseModel(c.file) }))
    // Pre-populate existence cache so opening any listed file skips the HTTP check
    _markKnownUrls(domainId, [...books, ...concepts])
    return { books, concepts }
  } catch (_) { return { books: [], concepts: [] } }
}

function _makeNavSidebar(initialDomain, initialFile) {
  const nav = document.createElement('nav')
  nav.className = 'cb-book-nav'

  const h = document.createElement('div')
  h.className = 'cb-book-nav__title'
  h.textContent = 'Concept Books'
  nav.appendChild(h)

  function _lbl(text) {
    const d = document.createElement('div')
    d.className = 'cb-book-nav__label'
    d.textContent = text
    return d
  }

  nav.appendChild(_lbl('Domain'))
  const domainSel = document.createElement('select')
  domainSel.className = 'cb-book-nav__select'
  nav.appendChild(domainSel)

  nav.appendChild(_lbl('Model'))
  const modelSel = document.createElement('select')
  modelSel.className = 'cb-book-nav__select'
  modelSel.innerHTML = '<option value="">— all —</option>'
  nav.appendChild(modelSel)

  nav.appendChild(_lbl('TOC Index'))
  const bookSel = document.createElement('select')
  bookSel.className = 'cb-book-nav__select'
  nav.appendChild(bookSel)

  nav.appendChild(_lbl('Concept'))
  const conceptSel = document.createElement('select')
  conceptSel.className = 'cb-book-nav__select'
  nav.appendChild(conceptSel)

  const openBtn = document.createElement('button')
  openBtn.textContent = 'Open'
  openBtn.disabled = true
  openBtn.className = 'cb-book-nav__open'
  nav.appendChild(openBtn)

  function _updateOpen() {
    openBtn.disabled = !domainSel.value || (!bookSel.value && !conceptSel.value)
  }

  let _allBooks = []
  let _allConcepts = []

  function _applyModelFilter() {
    const m = modelSel.value
    const filteredBooks = m ? _allBooks.filter(b => !b.model || b.model === m) : _allBooks
    const filteredConcepts = m ? _allConcepts.filter(c => !c.model || c.model === m) : _allConcepts
    bookSel.innerHTML = '<option value="">Select book…</option>'
    conceptSel.innerHTML = '<option value="">Select concept…</option>'
    filteredBooks.forEach(b => {
      const o = document.createElement('option')
      o.value = b.file; o.textContent = b.label
      if (b.file === initialFile) o.selected = true
      bookSel.appendChild(o)
    })
    filteredConcepts.forEach(c => {
      const o = document.createElement('option')
      o.value = c.file; o.textContent = c.label
      if (c.file === initialFile) o.selected = true
      conceptSel.appendChild(o)
    })
    _updateOpen()
  }

  async function _fillBooks(domainId) {
    bookSel.innerHTML = '<option value="">Loading…</option>'
    conceptSel.innerHTML = '<option value="">Loading…</option>'
    modelSel.innerHTML = '<option value="">Loading…</option>'
    _updateOpen()
    const { books, concepts } = await _loadDomainBooks(domainId)
    _allBooks = books
    _allConcepts = concepts

    // Populate model dropdown with unique models found in this domain
    const modelSet = new Set()
    books.forEach(b => { if (b.model) modelSet.add(b.model) })
    concepts.forEach(c => { if (c.model) modelSet.add(c.model) })
    const sortedModels = [...modelSet].sort()
    modelSel.innerHTML = '<option value="">— all —</option>'
    sortedModels.forEach(m => {
      const o = document.createElement('option')
      o.value = m; o.textContent = m
      modelSel.appendChild(o)
    })
    // Auto-select the model from initialFile if present, else default to sonnet
    const fileModel = initialFile ? parseModel(initialFile) : ''
    if (fileModel && modelSet.has(fileModel)) modelSel.value = fileModel
    else if (modelSet.has('sonnet')) modelSel.value = 'sonnet'

    _applyModelFilter()
  }

  async function _fillDomains() {
    domainSel.innerHTML = '<option value="">Loading…</option>'
    bookSel.innerHTML = '<option value="">—</option>'
    conceptSel.innerHTML = '<option value="">—</option>'
    _updateOpen()
    const domains = await _loadDomains()
    domainSel.innerHTML = '<option value="">Select domain…</option>'
    ;[...domains].sort((a, b) => a.localeCompare(b, 'zh')).forEach(id => {
      const o = document.createElement('option')
      o.value = id; o.textContent = id
      if (id === initialDomain) o.selected = true
      domainSel.appendChild(o)
    })
    if (domainSel.value) await _fillBooks(domainSel.value)
    else _updateOpen()
  }

  domainSel.addEventListener('change', () => {
    if (domainSel.value) _fillBooks(domainSel.value)
    else {
      bookSel.innerHTML = '<option value="">—</option>'
      conceptSel.innerHTML = '<option value="">—</option>'
      modelSel.innerHTML = '<option value="">— all —</option>'
      _allBooks = []
      _allConcepts = []
      _updateOpen()
    }
  })
  modelSel.addEventListener('change', _applyModelFilter)
  bookSel.addEventListener('change', () => {
    if (bookSel.value) conceptSel.value = ''
    _updateOpen()
  })
  conceptSel.addEventListener('change', () => {
    if (conceptSel.value) bookSel.value = ''
    _updateOpen()
  })
  openBtn.addEventListener('click', () => {
    const file = bookSel.value || conceptSel.value
    const d = domainSel.value
    if (file && d) window.location.hash = `/book?domain=${encodeURIComponent(d)}&file=${encodeURIComponent(file)}`
  })

  // Separator between picker and TOC
  const tocSep = document.createElement('div')
  tocSep.style.cssText = 'border-top:1px solid rgba(255,255,255,0.15);margin:10px 0 8px;flex-shrink:0'
  nav.appendChild(tocSep)

  const tocSection = document.createElement('div')
  tocSection.style.cssText = 'flex:1;overflow-y:auto;min-height:0;display:flex;flex-direction:column'
  tocSection.innerHTML = '<div style="color:#90b4e8;font-size:11px;padding:4px 0">Open a book to see contents.</div>'
  nav.appendChild(tocSection)
  nav.tocSection = tocSection

  _fillDomains()
  return nav
}

// ── Page ──────────────────────────────────────────────────────────────────────

export function BookPage(container, params) {
  const { domain, file: initialFile } = params || {}

  container.innerHTML = ''
  container.style.cssText = ''
  container.className = 'cb-book-page'

  container.appendChild(Header())

  const bodyRow = document.createElement('div')
  bodyRow.style.cssText = 'display:flex;flex:1;overflow:hidden'
  container.appendChild(bodyRow)

  const navEl = _makeNavSidebar(domain || '', initialFile || '')
  bodyRow.appendChild(navEl)

  const contentEl = document.createElement('div')
  contentEl.style.cssText = 'flex:1;display:flex;overflow:hidden;min-width:0'
  bodyRow.appendChild(contentEl)

  if (!domain || !initialFile) return

  const parsed = parseLevelLang(initialFile)
  let currentFile = initialFile
  const p1 = { level: parsed.level, lang: parsed.lang, model: parseModel(initialFile) }

  const rightCol = document.createElement('div')
  rightCol.style.cssText = 'flex:1;display:flex;flex-direction:column;overflow:hidden;min-width:0'
  contentEl.appendChild(rightCol)

  rightCol.appendChild(makeControlRow(null, p1, (key, val) => { p1[key] = val; reload() }, () => { _clearExistsCache(); reload() }))

  const frame = document.createElement('iframe')
  frame.style.cssText = 'flex:1;width:100%;border:none;display:block'
  rightCol.appendChild(frame)

  let isSrcdoc = false

  const _onConceptClick = href => {
    if (!href) return
    if (href.startsWith('#')) {
      try { frame.contentDocument?.querySelector(href)?.scrollIntoView({ behavior: 'smooth' }) } catch (_) {}
      return
    }
    currentFile = currentFile.replace(/[^/]+\.html$/, href)
    reload()
  }

  frame.addEventListener('load', () => {
    if (isSrcdoc) return
    try {
      const href = frame.contentWindow?.location?.href
      if (href && !href.startsWith('about:')) {
        const fname = decodeURIComponent(href.replace(/.*\/html\//, ''))
        if (fname && !fname.includes('://') && fname !== conceptFilename(currentFile)) {
          currentFile = currentFile.replace(/[^/]+\.html$/, fname)
        }
      }
    } catch (_) {}
    hideTocInFrame(frame)
    let hasToc = false
    try { hasToc = !!frame.contentDocument?.querySelector('nav.toc') } catch (_) {}
    if (!hasToc) return
    _fillTocSection(navEl.tocSection, frame, { onConceptClick: _onConceptClick })
  })

  function reload() {
    const url = buildUrl(domain, currentFile, p1.level, p1.lang, p1.model)
    _checkExists(url).then(exists => {
      isSrcdoc = !exists
      if (exists) { frame.src = url }
      else { frame.removeAttribute('src'); frame.srcdoc = _notFoundHtml(conceptFilename(currentFile), p1.model, p1.lang, p1.level) }
    })
  }

  reload()
}
